# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4a074596aa21140f9846f540ab3c6f8420a58a5279da57be8b09943ca10f15bc6ed1d361163087600d8de9b231c41fa96e8b5c08833844398bfe4d834e285abe
  mailgun_base_url: https://api:key-6b015c877a4c0cb07e1da996944922b6@api.mailgun.net/v2/sandbox92e1ab5ac66b43458a8a3c15a99a6421.mailgun.org/
  slack_web_hook: https://hooks.slack.com/services/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
  google_client_id: 374169068036-faqvcqq455p063h927rjiv418ehbff9u.apps.googleusercontent.com
  google_client_secret: VAp6WH1efwEyIo99pSwtU2-y
  linkedin_client_id: 75ap9kmjwh1saq
  linkedin_client_secret: OJSzI6ewsx52x48R
facebook_client_id: 108627286462499
facebook_client_secret: 412b74aeb9069f93d63140ad6794cd48
  # facebook_client_id: 1436962946605426
  # facebook_client_secret: aa6aa5dcc9625a5e385a633ba9f9e917

test:
  secret_key_base: 0fbe45c4326e2d8c4014988fc8af82b750dfd6e491b071a8a34c9c6dbb91adfc080c6451b672d2ac2ad78b82eca46b5ed748454821938d393068e62b3ac1f3e6
  mailgun_base_url: https://api:key-6b015c877a4c0cb07e1da996944922b6@api.mailgun.net/v2/sandbox92e1ab5ac66b43458a8a3c15a99a6421.mailgun.org/
  slack_web_hook: https://hooks.slack.com/services/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
  google_client_id: 374169068036-faqvcqq455p063h927rjiv418ehbff9u.apps.googleusercontent.com
  google_client_secret: VAp6WH1efwEyIo99pSwtU2-y
  linkedin_client_id: 75ap9kmjwh1saq
  linkedin_client_secret: OJSzI6ewsx52x48R
  facebook_client_id: 108627286462499
  facebook_client_secret: 412b74aeb9069f93d63140ad6794cd48
  # facebook_client_id: 1436962946605426
  # facebook_client_secret: aa6aa5dcc9625a5e385a633ba9f9e917

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  mailgun_base_url: <%= ENV["MAILGUN_BASE_URL"] %>
  slack_web_hook: <%= ENV["SLACK_WEB_HOOK"] %>
  google_client_id: <%= ENV["GOOGLE_CLIENT_ID"] %>
  google_client_secret: <%= ENV["GOOGLE_CLIENT_SECRET"] %>
  linkedin_client_id: <%= ENV["LINKEDIN_CLIENT_ID"] %>
  linkedin_client_secret: <%= ENV["LINKEDIN_CLIENT_SECRET"] %>
  facebook_client_id: <%= ENV["FACEBOOK_CLIENT_ID"] %>
  facebook_client_secret: <%= ENV["FACEBOOK_CLIENT_SECRET"] %>
